
services:
  db:
    container_name: auth_db
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authentication
    ports:
      - "5432:5432"

  back:
    build:
      context: .
    container_name: auth_java
    image: img_auth_java
    restart: always
    ports:
      - "8081:8081"
    expose:
      - 8081
    environment:
      TOKEN-SECRET: "hsdiofh398w5h48392hf8h23489f"
    depends_on:
      db:
        condition: service_started