server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  application:
    name: login
  datasource:
    url: jdbc:postgresql://localhost:5050/postgressql
    username: postgres
    password: aprender
  sql:
    init:
      mode: always
      encoding: utf-8
