server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
  port: 8081

spring:
  application:
    name: login

  datasource:
    url: jdbc:postgresql://db:5432/authentication
    username: postgres
    password: postgres

  sql:
    init:
      mode: always
      encoding: utf-8

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

environment:
  token-secret: ${TOKEN-SECRET}