server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  application:
    name: login

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Postgres

  sql:
    init:
      mode: always
      encoding: utf-8

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
