server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include:
          - log
          - health
          - mappings
        exclude:
          - env
          - beans

spring:
  application:
    name: login

  datasource:
    url: jdbc:postgresql://${DATA_BASE}:5432/authentication
    username: postgres
    password: postgres

  sql:
    init:
      mode: always
      encoding: utf-8

  jpa:
    show-sql: ${SHOW_SQL}
    hibernate:
      ddl-auto: update
    open-in-view: false

environment:
  token-secret: ${TOKEN_SECRET}