services:
  back:
    container_name: authentication
    image: auth_java
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_started

  db:
    container_name: auth_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authentication
    ports:
      - "5432:5432"
